# Generated by Django 5.2.1 on 2025-06-08 10:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.FloatField()),
                ('protein_g', models.FloatField()),
                ('carbs_g', models.FloatField()),
                ('fats_g', models.FloatField()),
                ('sugar_g', models.FloatField()),
                ('fiber_g', models.FloatField()),
                ('glycemic_index', models.FloatField(blank=True, null=True)),
                ('food_type', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non-Vegetarian'), ('vegan', 'Vegan'), ('eggetarian', 'Eggetarian'), ('other', 'Other')], default='other', max_length=20)),
                ('suitable_for_conditions', models.CharField(choices=[('none', 'None'), ('diabetes', 'Diabetes'), ('thyroid', 'Thyroid'), ('hypertension', 'Hypertension')], default='none', help_text='Health condition this food is suitable for', max_length=50)),
                ('suitable_for_goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('maintain', 'Maintain Weight'), ('gain_weight', 'Gain Weight')], default='maintain', help_text='Goal this food is suitable for', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='Enter the quantity of the food item')),
                ('unit', models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Liters'), ('cup', 'Cup'), ('bowl', 'Bowl'), ('piece', 'Piece'), ('tbsp', 'Tablespoon'), ('tsp', 'Teaspoon'), ('slice', 'Slice'), ('other', 'Other')], default='g', max_length=10)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('consumed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, help_text='Any additional notes about the meal')),
                ('calories', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Light Activity'), ('moderate', 'Moderate Activity'), ('active', 'Active'), ('very_active', 'Very Active')], max_length=50)),
                ('goal', models.CharField(choices=[('lose_weight', 'Lose Weight'), ('maintain', 'Maintain Weight'), ('gain_weight', 'Gain Weight')], max_length=20)),
                ('diet_type', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non-Vegetarian'), ('vegan', 'Vegan'), ('eggetarian', 'Eggetarian'), ('other', 'Other')], default='other', max_length=20)),
                ('health_conditions', models.TextField(blank=True, help_text='e.g., hypertension')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiabeticProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hba1c', models.FloatField(help_text='HbA1c level (%)')),
                ('fasting_blood_sugar', models.FloatField(help_text='Fasting Blood Sugar (mg/dL)')),
                ('insulin_dependent', models.BooleanField(default=False)),
                ('medications', models.TextField(blank=True, null=True)),
                ('diagnosis_date', models.DateField()),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile')),
            ],
        ),
    ]
