# Generated by Django 5.2.1 on 2025-05-28 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_fooditem_dietrecommendation_diabeticrecommendation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietrecommendation',
            name='recommended_foods',
        ),
        migrations.RemoveField(
            model_name='dietrecommendation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermeal',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='usermeal',
            name='user',
        ),
        migrations.DeleteModel(
            name='DiabeticRecommendation',
        ),
        migrations.DeleteModel(
            name='DietRecommendation',
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
        migrations.DeleteModel(
            name='UserMeal',
        ),
    ]
