# Generated by Django 5.2.1 on 2025-06-10 19:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_diabeticprofile_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='health_conditions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('diabetes', 'Diabetes'), ('hypertension', 'Hypertension'), ('thyroid', 'Thyroid'), ('cholesterol', 'Cholesterol'), ('pcos', 'PCOS/PCOD'), ('anemia', 'Anemia'), ('cancer', 'Cancer'), ('none', 'None')], max_length=20), blank=True, default=list, help_text='List of health conditions', size=None),
        ),
    ]
