# Generated by Django 5.2.1 on 2025-06-08 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_fooditem_usermeal_userprofile_diabeticprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True)),
                ('new_users', models.IntegerField()),
                ('active_patients', models.IntegerField()),
                ('total_revenue', models.FloatField()),
                ('feedback_summary', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Normal User (Patient)'), ('nutritionist', 'Nutritionist'), ('admin', 'Admin'), ('owner', 'Owner'), ('operator', 'Operator')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='NutritionistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_level', models.PositiveSmallIntegerField(choices=[(1, 'Basic'), (2, 'Senior')], default=1)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'nutritionist'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('reminder_time', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'user'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
