# Generated by Django 5.2.1 on 2025-05-28 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_dietrecommendation_recommended_foods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='diet_type',
            field=models.CharField(choices=[('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non-Vegetarian'), ('vegan', 'Vegan'), ('eggetarian', 'Eggetarian'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='DiabeticProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hba1c', models.FloatField(help_text='HbA1c level (%)')),
                ('fasting_blood_sugar', models.FloatField(help_text='Fasting Blood Sugar (mg/dL)')),
                ('insulin_dependent', models.BooleanField(default=False)),
                ('medications', models.TextField(blank=True, null=True)),
                ('diagnosis_date', models.DateField()),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile')),
            ],
        ),
    ]
