# Generated by Django 5.2.1 on 2025-06-08 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appreport_user_role_nutritionistprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeal',
            name='food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.fooditem'),
        ),
        migrations.AlterField(
            model_name='usermeal',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
