# Generated by Django 5.2.1 on 2025-06-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile_diet_type_userprofile_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_diabetic',
        ),
    ]
