# Generated by Django 5.2.1 on 2025-06-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usermeal_food_item_alter_usermeal_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeal',
            name='carbs',
            field=models.FloatField(blank=True, help_text='Carbohydrates in grams', null=True),
        ),
        migrations.AddField(
            model_name='usermeal',
            name='fats',
            field=models.FloatField(blank=True, help_text='Fats in grams', null=True),
        ),
        migrations.AddField(
            model_name='usermeal',
            name='fiber',
            field=models.FloatField(blank=True, help_text='Fiber in grams', null=True),
        ),
        migrations.AddField(
            model_name='usermeal',
            name='food_name',
            field=models.CharField(blank=True, help_text='Name of the food item', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usermeal',
            name='protein',
            field=models.FloatField(blank=True, help_text='Protein in grams', null=True),
        ),
        migrations.AddField(
            model_name='usermeal',
            name='sugar',
            field=models.FloatField(blank=True, help_text='Sugar in grams', null=True),
        ),
    ]
