# Generated by Django 5.2.1 on 2025-06-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_usermeal_carbs_usermeal_fats_usermeal_fiber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='suitable_for_conditions',
            field=models.CharField(choices=[('none', 'None'), ('diabetes', 'Diabetes'), ('thyroid', 'Thyroid'), ('hypertension', 'Hypertension')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='suitable_for_goal',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss'), ('maintain', 'Maintain Weight'), ('gain_weight', 'Gain Weight')], default='maintain', max_length=20),
        ),
        migrations.AlterField(
            model_name='usermeal',
            name='carbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermeal',
            name='fats',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermeal',
            name='fiber',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermeal',
            name='food_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usermeal',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermeal',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='usermeal',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='usermeal',
            name='sugar',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
