# Generated by Django 5.2.1 on 2025-06-02 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_fooditem_usermeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeal',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
        ),
    ]
