# Generated by Django 5.2.1 on 2025-06-08 21:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userprofile_country_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientreminder',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientreminder',
            name='reminder_time',
        ),
        migrations.RemoveField(
            model_name='patientreminder',
            name='sent',
        ),
        migrations.AddField(
            model_name='patientreminder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientreminder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientreminder',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patientreminder',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientreminder',
            name='title',
            field=models.CharField(default='General Reminder', max_length=255),
        ),
        migrations.AddField(
            model_name='patientreminder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patientreminder',
            name='message',
            field=models.TextField(blank=True, default='No message provided.'),
        ),
    ]
