# Generated by Django 5.2.1 on 2025-06-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_usermeal_food_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermeal',
            name='food_item',
        ),
    ]
