# Generated by Django 5.2.1 on 2025-06-08 21:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_patientreminder_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreminder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
