# Generated by Django 5.2.1 on 2025-06-08 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_patientreminder_patient_and_more'),
        ('app', '0010_alter_patientreminder_date'),
    ]

    operations = [
    ]
